const jobTitle = [
    {"title": "Accountant"},
    {"title": "Marketing Manager"},
    {"title": "Human Resources Specialist"},
    {"title": "Project Manager"},
    {"title": "Sales Representative"},
    {"title": "Customer Service Representative"},
    {"title": "Operations Manager"},
    {"title": "Graphic Designer"},
    {"title": "Executive Assistant"},
    {"title": "Event Planner"},
    {"title": "Teacher"},
    {"title": "Nurse"},
    {"title": "Police Officer"},
    {"title": "Chef"},
    {"title": "Journalist"},
    {"title": "Retail Manager"},
    {"title": "Electrician"},
    {"title": "Plumber"},
    {"title": "Mechanic"},
    {"title": "Librarian"},
    {"title": "Social Worker"},
    {"title": "Architect"},
    {"title": "Interior Designer"},
    {"title": "Bank Teller"},
    {"title": "Flight Attendant"},
    {"title": "Hotel Manager"},
    {"title": "Insurance Agent"},
    {"title": "Real Estate Agent"},
    {"title": "Legal Assistant"},
    {"title": "Receptionist"},
    {"title": "Personal Trainer"},
    {"title": "Pharmacist"},
    {"title": "Dentist"},
    {"title": "Physical Therapist"},
    {"title": "Veterinarian"},
    {"title": "Photographer"},
    {"title": "Counselor"},
    {"title": "Financial Advisor"},
    {"title": "Social Media Manager"},
    {"title": "Editor"},
    {"title": "Translator"},
    { title: 'Software Engineer' },
  { title: 'Data Scientist' },
  { title: 'UX Designer' },
  { title: 'Product Manager' },
  { title: 'Graphic Designer' },
  { title: 'Project Manager' },
  { title: 'Marketing Specialist' },
  { title: 'Financial Analyst' },
  { title: 'Human Resources Manager' },
  { title: 'Sales Representative' },
  { title: 'Customer Support Specialist' },
  { title: 'Content Writer' },
  { title: 'Cybersecurity Analyst' },
  { title: 'Software Developer' },
  { title: 'Data Analyst' },
  { title: 'Business Analyst' },
  { title: 'UX/UI Developer' },
  { title: 'Quality Assurance Engineer' },
  { title: 'Systems Administrator' },
  { title: 'Network Engineer' },
  { title: 'DevOps Engineer' },
  { title: 'Technical Writer' },
  { title: 'Web Developer' },
  { title: 'Front-End Developer' },
  { title: 'Back-End Developer' },
  { title: 'Full Stack Developer' },
  { title: 'Mobile App Developer' },
  { title: 'UI/UX Designer' },
  { title: 'Product Designer' },
  { title: 'Scrum Master' },
  { title: 'Agile Coach' },
  { title: 'IT Manager' },
  { title: 'IT Consultant' },
  { title: 'Database Administrator' },
  { title: 'Business Intelligence Analyst' },
  { title: 'Cloud Solutions Architect' },
  { title: 'Machine Learning Engineer' },
  { title: 'AI Specialist' },
  { title: 'Blockchain Developer' },
  { title: 'IT Security Specialist' },
  { title: 'Network Security Engineer' },
  { title: 'Systems Analyst' },
  { title: 'IT Support Specialist' },
  { title: 'Technical Support Engineer' },
  { title: 'Software Architect' },
  { title: 'Systems Integration Engineer' },
  { title: 'Data Engineer' },
  { title: 'Network Administrator' },
  { title: 'ERP Consultant' },
  { title: 'QA Automation Engineer' },
  { title: 'IT Project Manager' },
  { title: 'Site Reliability Engineer (SRE)' },
  { title: 'UX Researcher' },
  { title: 'Content Strategist' },
  { title: 'Digital Marketing Manager' },
  { title: 'SEO Specialist' },
  { title: 'E-commerce Specialist' },
  { title: 'Social Media Manager' },
  { title: 'Game Developer' },
  { title: 'Virtual Reality Developer' },
  { title: 'Augmented Reality Developer' },
  { title: 'Automation Engineer' },
  { title: 'IT Auditor' },
  { title: 'System Design Engineer' },
  { title: 'Software Development Manager' },
  { title: 'Network Operations Center (NOC) Engineer' },
  { title: 'IT Trainer' },
  { title: 'Data Architect' },
  { title: 'AI Ethics Specialist' },
  { title: 'Chatbot Developer' },
  { title: 'IT Compliance Analyst' },
  { title: 'Health IT Specialist' },
  { title: 'Information Security Analyst' },
  { title: 'Business Continuity Planner' },
  { title: 'ITIL Process Consultant' },
  { title: 'Technical Recruiter' },
  { title: 'AI Product Manager' },
  { title: 'Robotic Process Automation (RPA) Developer' },
  { title: 'Quantum Computing Engineer' },
  { title: 'Geospatial Analyst' },
  { title: 'IT Business Analyst' },
  { title: 'IT Procurement Specialist' },
  { title: 'Technical Illustrator' },
  { title: 'Knowledge Manager' },
  { title: 'IT Change Manager' },
  { title: 'Ethical Hacker' },
  { title: 'Systems Thinking Facilitator' },
  { title: 'Microservices Developer' },
  { title: 'Cloud Migration Specialist' },
  { title: 'IT Service Desk Analyst' },
  { title: 'IT Risk Analyst' },
  { title: 'AI Trainer' },
  { title: 'Cybersecurity Incident Responder' },
  { title: 'Digital Forensic Analyst' },
  { title: 'IT Sales Executive' },
  { title: 'Business Process Analyst' },
  { title: 'ChatOps Engineer' },
  { title: 'Technology Evangelist' },
  { title: 'Quantitative Analyst' },
  { title: 'Low-Code Developer' },
  { title: 'Business Systems Analyst' },
  { title: 'IT Operations Manager' },
  { title: 'Technical Product Owner' },
  { title: 'AR/VR Interaction Designer' },
  { title: 'Data Protection Officer' },
  { title: 'IT Asset Manager' },
  { title: 'Quantum Algorithms Developer' },
  { title: 'Augmented Reality Content Developer' },
  { title: 'Virtual Reality Content Developer' },
  { title: 'Edge Computing Engineer' },
  { title: 'IT Facilities Manager' },
  { title: 'AI Chatbot Trainer' },
  { title: 'Blockchain Solution Architect' },
  { title: 'Data Governance Specialist' },
  { title: 'IT Service Continuity Manager' },
  { title: 'IoT Solutions Architect' },
  { title: 'AI Model Validator' },
  { title: 'Quantum Cryptographer' },
  { title: 'AI System Integrator' },
  { title: 'IT Sustainability Specialist' },
  { title: 'Digital Twin Engineer' },
  { title: 'Neurotechnology Engineer' },
  { title: 'IT Accessibility Specialist' },
  { title: 'Robotic Process Automation (RPA) Consultant' },
  { title: 'Quantum Machine Learning Engineer' },
  { title: 'Geospatial Data Scientist' },
  { title: 'Cloud Engineer' },
  { title: 'Node.js Developer' },
  { title: 'Python Developer' },
  { title: 'React Developer' },
  { title: 'Angular Developer' },
  { title: 'Vue.js Developer' },
  { title: 'Java Developer' },
  { title: 'C# Developer' },
  { title: 'PHP Developer' },
  { title: 'Ruby on Rails Developer' },
  { title: 'Swift Developer' },
  { title: 'Kotlin Developer' },
  { title: 'Android Developer' },
  { title: 'iOS Developer' },
  { title: 'Unity Developer' },
  { title: '.NET Developer' },
  { title: 'Back-End Web Developer' },
  { title: 'Mobile App Developer' },
  { title: 'UI Developer' },
  { title: 'Game Developer' },
  { title: 'Virtual Reality Developer' },
  { title: 'Augmented Reality Developer' },
  { title: 'Cloud Solutions Architect' },
  { title: 'Machine Learning Engineer' },
  { title: 'AI Specialist' },
  { title: 'Blockchain Developer' },
  { title: 'Database Administrator' },
  { title: 'DevOps Engineer' },
  { title: 'System Administrator' },
  { title: 'Network Engineer' },
  { title: 'IT Security Specialist' },
  { title: 'Technical Writer' },
  { title: 'QA Engineer' },
  { title: 'IT Project Manager' },
  { title: 'IT Consultant' },
  { title: 'Technical Support Engineer' },
  { title: 'Cybersecurity Analyst' },
  { title: 'Data Scientist' },
  { title: 'Business Analyst' },
  { title: 'Business Intelligence Analyst' },
  { title: 'Cloud Solutions Architect' },
  { title: 'IT Manager' },
  { title: 'UX Designer' },
  { title: 'Product Manager' },
  { title: 'Marketing Specialist' },
  { title: 'Content Writer' },
  { title: 'Digital Marketing Manager' },
  { title: 'SEO Specialist' },
  { title: 'E-commerce Specialist' },
  { title: 'Social Media Manager' },
  { title: 'Technical Recruiter' },
  { title: 'IT Trainer' },
  { title: 'AI Trainer' },
  { title: 'Technical Illustrator' },
  { title: 'Chatbot Developer' },
  { title: 'IT Auditor' },
  { title: 'Information Security Analyst' },
  { title: 'Ethical Hacker' },
  { title: 'Data Engineer' },
  { title: 'Network Administrator' },
  { title: 'ERP Consultant' },
  { title: 'QA Automation Engineer' },
  { title: 'ITIL Process Consultant' },
  { title: 'Quantum Computing Engineer' },
  { title: 'IoT Solutions Architect' },
  { title: 'AR/VR Interaction Designer' },
  { title: 'Data Protection Officer' },
  { title: 'AI Model Validator' },
  { title: 'IT Service Delivery Manager' },
  { title: 'Digital Twin Engineer' },
  { title: 'Neurotechnology Engineer' },
  { title: 'IT Accessibility Specialist' },
  { title: 'Robotic Process Automation (RPA) Consultant' },
  { title: 'Quantum Machine Learning Engineer' },
  { title: 'Geospatial Data Scientist' },
  { title: 'Cloud Engineer' },
  { title: 'Node.js Developer' },
  { title: 'Python Developer' },
  { title: 'React Developer' },
  { title: 'Angular Developer' },
  { title: 'Vue.js Developer' },
  { title: 'Java Developer' },
  { title: 'C# Developer' },
  { title: 'PHP Developer' },
  { title: 'Ruby on Rails Developer' },
  { title: 'Swift Developer' },
  { title: 'Kotlin Developer' },
  { title: 'Android Developer' },
  { title: 'iOS Developer' },
  { title: 'Unity Developer' },
  { title: '.NET Developer' },
  { title: 'Front-End Web Developer' },
  { title: 'Back-End Web Developer' },
  { title: 'Full Stack Web Developer' },
  { title: 'Mobile App Developer' },
  { title: 'UI/UX Designer' },
  { title: 'UI Developer' },
  { title: 'UX Designer' },
  { title: 'Game Developer' },
  { title: 'Virtual Reality Developer' },
  { title: 'Augmented Reality Developer' },
]

export default jobTitle;